[*] Running ...
[*] Dataset loaded: D:\MCTS-AHD-master\problems\tsp_constructive\dataset\train50_dataset.npy with 64 instances.
D:\MCTS-AHD-master\problems\tsp_constructive\gpt.py:32: RuntimeWarning: invalid value encountered in scalar power
  path_potential = (weighted_immediate ** 1.1) + base_decay * (weighted_potential ** 0.9)
Traceback (most recent call last):
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 82, in <module>
    obj = eval_heuristic(node_positions[i])
  File "D:\MCTS-AHD-master\problems\tsp_constructive\eval.py", line 52, in eval_heuristic
    raise KeyError(f"Node {next_node} is already visited.")
KeyError: 'Node None is already visited.'
